### ISSUE TITLE
TODO: Add color gradient for values in each column

### ISSUE THREAD

**Issue by roengle** [Wup123102/VexInfo#25]
Use conditional formatting to create a color gradient used for each column to allow for easy comparisons between data points.

**Comment by Wup123102** [comment]
A potential configuration for the conditional format request:

![API Test Configuration](https://user-images.githubusercontent.com/15174340/54629816-98df3d80-4a35-11e9-89de-cecf8b1ce28c.png)

**Comment by roengle** [comment]
Tentative configuration for the conditional format request:
![Screenshot (18)](https://user-images.githubusercontent.com/15174340/55102683-3369fd00-5084-11e9-914c-603656a0f2d3.png)

**Comment by roengle** [comment]
Quick Note: Each column must be done individually so that the cells are highlighted based on the relative data to the column, not the whole data set. 

This can be done by using a loop, since the only thing that would change between each individual conditional format would be the startColumnIndex and endColumnIndex.

EDIT: The gradient does not mess up if individual ranges for each column are used.

**Comment by roengle** [comment]
Almost done. The gradient does not represent data in each individual column, like it should. 

![Image1](https://i.gyazo.com/f077d9ac20952141b64eb0617457c722.png)

**Comment by roengle** [comment]
Instead of adding ranges using a for loop, a bunch of different conditional formats can be done for each column(this would be encapsulated in its own respective loop.) Solution is a bit sloppy, in the end having a ton of conditional formatting, but _should_ get the job done.

**Comment by roengle** [comment]
done(https://github.com/Wup123102/ReadFromVexDB/commit/5c3fcb5f3758da9f5f96876418bc8d400e902e54)
